sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    - jorgelca1205@gmail.com
node_js:
  - '10'
install:
  - yarn
jobs:
  include:
    - stage: build packages
      script:
        - yarn build
branches:
  only: master
